# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 07:08
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161122_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('genre', models.IntegerField(verbose_name='类别')),
                ('content', ckeditor.fields.RichTextField(verbose_name='正文')),
                ('tag', models.CharField(max_length=100, verbose_name='标签')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='发表时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '博客列表',
                'verbose_name_plural': '博客列表',
            },
        ),
    ]
