# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.TextField(default='this is abstract', max_length=255, verbose_name='摘要'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标签'),
        ),
    ]
