# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 05:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='关注时间')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans', to=settings.AUTH_USER_MODEL, verbose_name='被关注者')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guanzhu', to=settings.AUTH_USER_MODEL, verbose_name='关注者')),
            ],
        ),
    ]
