# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-26 12:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='发表时间'),
        ),
    ]
