# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-26 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20161226_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发表时间'),
        ),
    ]
